name: deploying

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        
        steps:
          - name: Deploying to servers
            env:
              SSH_KEY: ${{secrets.SSH_KEY}}
              SSH_USER: ${{secrets.SSH_USER}}
              SSH_HOST: ${{secrets.SSH_HOST}}
            run: |
              echo "$SSH_KEY" > myKey.pem
              chmod 600 myKey.pem
              ssh -i myKey.pem $SSH_USER@$SSH_HOST "cd docker-compose-flask-app && git pull https://github.com/Nightylol911/test-capstone.git && docker compose up -d --build"